kind: Pod
apiVersion: v1
metadata: 
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
## by default nginx will run on port: 80, so here it is not required to provide ports.