kind: Pod
apiVersion: v1
metadata: 
  name: multi-container
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: alma
    image: "almalinex:9"
    command: ["sleep", "2000"]