kind: Pod
apiVersion: v1
metadata: 
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    
    #case-1: refering to the individual keys
    # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:        ## refering the individual keys from 08-configmap.yaml file
    #       name: configmap-test
    #       key: course
    # - name: description
    #   valueFrom:
    #     configMapKeyRef:
    #       name: configmap-test
    #       key: description

    #case-2: refering to the complete configmap.yaml file
    envFrom:
    - configMapRef:
        name: configmap-test
        # refering to the complete configmap file instead of individual keys
