kind: Secret
apiVersion: v1
metadata: 
  name: secrets
data: 
  username: "YWRtaW4K"
  password: "YWRtaW4xMjMK"

## values are encrypted 
## echo admin | base64 ---> YWRtaW4K
## echo admin123 | base64 ---> YWRtaW4xMjMK