kind: Pod
apiVersion: v1
metadata: 
  name: pod-secrets
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: secrets     # refering to the secrets in 10-secrets.yaml file
