apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port

# here we didn't mention any "type" so by default the type will be "clusterIP"
# this service(nginx) will connect to the pod which has all the selector values(name, project, component and environment)  ---> it connects to the pod created using 12-nginx.yaml file.
