apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port
    nodePort: 32760
# valid port range is: 30000 - 32767, if we don't give then it will assign some random port.
# this service(nginx-np) will connect to the pod which has all the selector values(name, project, component and environment)  ---> it connects to the pod created using 12-nginx.yaml file.