kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  # these labels are deployment related labels
  labels:
    app: nginx              #labels we can give anythig as required
    purpose: deployment
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: test-project
  # pod definition
  template:
    metadata: 
      labels:
        app: nginx
        tier: web
        project: test-project
        extra-key: extra-value
    spec:
      containers:
      - name: nginx
        #image: nginx             # 1st run
        image: nginx:stable-perl  # 2nd run
# with the 2nd run, k8s will create new pods by deleting the existing pods after serving the pending requests if any.

          

